### ISSUE TITLE
Socket.IO

### ISSUE THREAD

**Issue by mattficke** [ga-wdi-exercises/teach-yourself#10]
https://github.com/mattficke/websockets

Comfort: 4

I'm having a little trouble integrating sessions into this, any pointers?

**Comment by RoselPadilla** [comment]
Works pretty well! Opened two tabs @ localhost:3000 and each updates as it should. Nice job.

**Comment by pdoulatshahi** [comment]
Looks great! Real-time messaging is something we haven't tackled in class so I was definitely interested to check this out.

https://github.com/mattficke/websockets/blob/master/public/styles.css#L2

:+1:
